name: uistate
description: The cleanest way of representing UIState in a flutter widget.
version: 1.0.8
homepage: 'https://github.com/cesarferreira/UIState'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
