name: uistate
description: The cleanest way of representing UIState in a flutter widget.
version: 1.0.7
homepage: 'https://github.com/cesarferreira/UIState'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
